services:
  clickhouse:
    image: docker.io/clickhouse:25.7.4.11
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    volumes:
      - local_cafe_dev_clickhouse_data:/var/lib/clickhouse/
  db:
    image: docker.io/postgres:17.4-bullseye
    environment:
      POSTGRES_DB: local_cafe_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - local_cafe_dev_data:/var/lib/postgresql/data
  # attack-blob:
  #   image: docker.io/fullstacking/attack-blob:latest
  #   ports:
  #     - "4001:4001"
  #   environment:
  #     PHX_HOST: localhost
  #     PORT: 4001
  #     MIX_ENV: dev
  #     SECRET_KEY_BASE: 9YdznIxisKy/L8EM2Of5eMRRssFK/iV3ZyBlYmxGc83G4wouqOy1CIMsC4VJLsc3
  #   volumes:
  #     - local_cafe_dev_blob_data:/app/data

volumes:
  local_cafe_dev_data:
  local_cafe_dev_clickhouse_data:
  # local_cafe_dev_blob_data:
